linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - dupword
    - godot
    - godox
    - misspell
    - gofmt
    - lll
    - testableexamples
    - testpackage
    - paralleltest
    - tparallel
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
